AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: backend for qrvey test
        
Resources:
    QrveyLambdaBackendIAMRole:     
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub "${AWS::StackName}-QrveyBackendLambda" 
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: Allow
                        Principal:
                            Service:
                                - 'lambda.amazonaws.com'                             
                        Action:
                            - 'sts:AssumeRole'
            Policies:
                -
                    PolicyName: !Sub "${AWS::StackName}-QrveyBackendLambdaIAMPolicy"
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                            -
                                Effect: Allow
                                Action:
                                    - logs:*
                                    - dynamodb:*
                                    - autoscaling:CompleteLifecycleAction
                                    - lambda:*
                                    - s3:*                
                                Resource: "*"                                                                                
    
    ApiGateway:
        Type: "AWS::Serverless::Api"
        Properties:
            Name: !Sub "${AWS::StackName}"
            StageName: Develop
            Variables:
                ApiGateway: !Ref ApiGateway
                region: !Ref AWS::Region


    CreateSuperheroe:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: dist/
            Description: 'Create a superhero in a database'
            Handler: src/functions/superheroesHandler.createSuperheroe
            Role: !GetAtt QrveyLambdaBackendIAMRole.Arn
            Runtime: nodejs12.x
            Timeout: 10
            Events:
                PostDynamoDBEndPointHTTP:
                    Type: Api
                    Properties:
                        Path: /createSuperheroe
                        Method: POST   
                        RestApiId: !Ref ApiGateway         
 
    GetHero:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: dist/
            Description: 'Get a superhero from a table'
            Handler: src/functions/superheroesHandler.getSuperheroe
            Role: !GetAtt QrveyLambdaBackendIAMRole.Arn
            Runtime: nodejs12.x
            Timeout: 10
            Events:
                GetDynamoDBEndPointHTTP:
                    Type: Api
                    Properties:
                        Path: /getSuperhero/{id}
                        Method: GET   
                        RestApiId: !Ref ApiGateway         
          
    DeleteSuperhero:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: dist/
            Description: 'Delete a superhero in the database'
            Handler: src/functions/superheroesHandler.deleteSuperheroe
            Role: !GetAtt QrveyLambdaBackendIAMRole.Arn
            Runtime: nodejs12.x
            Timeout: 10
            Events:
                DeleteDynamoDBEndPointHTTP:
                    Type: Api
                    Properties:
                        Path: /deleteSuperhero/{id}
                        Method: DELETE   
                        RestApiId: !Ref ApiGateway         
                       
    UpdateSuperhero:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: dist/
            Description: 'Update a superhero in the database'
            Handler: src/functions/superheroesHandler.updateSuperheroe
            Role: !GetAtt QrveyLambdaBackendIAMRole.Arn
            Runtime: nodejs12.x
            Timeout: 10
            Events:
                PatchDynamoDBEndPointHTTP:
                    Type: Api
                    Properties:
                        Path: /updateSuperhero
                        Method: PATCH   
                        RestApiId: !Ref ApiGateway         
                       
    ListSuperheroes:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: dist/
            Description: 'Get all the superheroes'
            Handler: src/functions/superheroesHandler.listSuperheroes
            Role: !GetAtt QrveyLambdaBackendIAMRole.Arn
            Runtime: nodejs12.x
            Timeout: 10
            Events:
                ListDynamoDBEndPointHTTP:
                    Type: Api
                    Properties:
                        Path: /listSuperheroes
                        Method: GET   
                        RestApiId: !Ref ApiGateway

    CreateExcelReport:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: dist/
            Description: 'Get all the superheroes for create a excel report'
            Handler: src/functions/excelReportHandler.excelSuperheroesReport
            Role: !GetAtt QrveyLambdaBackendIAMRole.Arn
            Runtime: nodejs12.x
            Timeout: 10
            Events:
                ReportCsvEndPointHTTP:
                    Type: Api
                    Properties:
                        Path: /excelReport
                        Method: GET   
                        RestApiId: !Ref ApiGateway 

    CreatePdfReport:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: dist/
            Description: 'Get all the superheroes for create a pdf report'
            Handler: src/functions/pdfReportHandler.pdfSuperheroesReports
            Role: !GetAtt QrveyLambdaBackendIAMRole.Arn
            Runtime: nodejs12.x
            Timeout: 10
            Events:
                ReportPdfEndPointHTTP:
                    Type: Api
                    Properties:
                        Path: /pdfReport
                        Method: GET   
                        RestApiId: !Ref ApiGateway 
