AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Dynamo backend serverless application Accounts Domain
Resources:

  SuperheroesTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-superheroes-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S  

      KeySchema:
        -
          KeyType: HASH
          AttributeName: id
        
Outputs:
  SuperheroesTableArn:
    Description: "Superheroes Table Arn"
    Value: !GetAtt SuperheroesTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SuperheroesTableArn"